title: Phoenix Guild Hub
email: buinoff@gmail.com
description: >-
  Портал гильдий True Phoenix и Phoenix Nest.

markdown: kramdown

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "nest"
    values:
      layout: "nest-default"
      author: "Phoenix Nest Team"

  - scope:
      path: ""
    values:
      layout: "true-default"

exclude:
  - vendor/
  - .bundle/
  - .github/
  - README.md

permalink: pretty