backend:
  name: github
  repo: ТВОЯ_ОРГАНИЗАЦИЯ/РЕПОЗИТОРИЙ
  branch: dev # Пока работаем в dev

media_folder: "nest/assets/images/uploads"
public_folder: "/nest/assets/images/uploads"

collections:
  - name: "nest_news"
    label: "Новости Гнезда"
    folder: "nest/_posts" # Только новости из папки nest
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}